### ISSUE TITLE
hi yeah, I have an issue.

### ISSUE THREAD

**Issue by MrCloudz** [Brendonovich/hangman#1]
It's such a disgrace, what such a bad issue.

ISSUE: This isn't a billion dollar app.

Smh.

**Comment by Brendonovich** [comment]
does it look like a billion dollar app
![image](https://user-images.githubusercontent.com/14191578/116534981-cb96d800-a915-11eb-9905-40b79b3e053a.png)

**Comment by MrCloudz** [comment]
With a touch of inspect element... anything can be a billion dollar app.

<img width="215" alt="Screen Shot 2021-04-29 at 10 11 53 PM" src="https://user-images.githubusercontent.com/55217660/116535537-f4c86000-a937-11eb-8aa5-d1025d937a73.png">

**Comment by Brendonovich** [comment]
if you can fix this then it'll be a start
![image](https://user-images.githubusercontent.com/14191578/116535906-e6b61780-a916-11eb-8a92-8a07e1d7c2fe.png)

**Comment by MrCloudz** [comment]
Have you thought of just making it work the first time... so then you don't have an error? If you don't have errors ever, then you don't have to deal with them...

200IQ
